### ISSUE TITLE
Support For PHP 8.1

### ISSUE THREAD

**Issue by lijithmg** [techdivision/valet-plus#48]
Can we have the support for PHP version 8.1

@zelgerj

**Comment by lijithmg** [comment]
@zelgerj https://github.com/weprovide/valet-plus/pull/605/files this commit helps me to switch to 8.1 version of PHP

**Comment by zelgerj** [comment]
@lijithmg Thanks for the information. We are no longer actively developing this fork from https://github.com/weprovice/valet-plus. We have now started our own project which is similar to the concept but uses completely different technologies. Maybe that would be something for you. See https://github.com/valet-sh/valet-sh and https://valet.sh
